import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Pricing from "@/components/pricing/Pricing";
import Action_Buttons from "@/components/action-buttons/Action_Buttons";
import Main_Section from "@/components/main/Main_Section";
import CookieProvider from "./CookieProvider";
import ClientProvider from "./ClientProvider";
import RecoilContextProvider from "./RecoilContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Naai-POS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("HELLO");
  return (
    <html lang="en">
      <body className={inter.className}>
        <CookieProvider>
          <Header />
          <div className="flex w-screen overflow-hidden">
            {/* <Action_Buttons /> */}
            <Main_Section>{children}</Main_Section>
            <Pricing />
          </div>
        </CookieProvider>
      </body>
    </html>
  );
}
