import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Pricing from "@/components/pricing/Pricing";
import Action_Buttons from "@/components/action-buttons/Action_Buttons";
import Main_Section from "@/components/main/Main_Section";
import CookieProvider from "./CookieProvider";
import ClientProvider from "./ClientProvider";
import RecoilContextProvider from "./RecoilContextProvider";
import MainWrapper from "@/components/mainWrapper/mainWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Naai-POS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("HELLO");
  return (
    <html lang="en">
      <body className={inter.className}>
        <CookieProvider>
          <MainWrapper
            name="POS"
            parentWrapper={{
              className: "flex flex-col sm:gap-4 sm:py-4 sm:pl-14 h-full bg-[#FAFBFD]",
            }}
            mainWrapper={{
              className:
                "grid flex-1 items-start gap-4 p-2 sm:px-6 sm:py-0 md:gap-8 h-full bg-[#FAFBFD]",
            }}
          >
            <div className="flex w-full overflow-hidden h-[calc(100vh-6rem)]">
              {/* <Action_Buttons /> */}
              <Main_Section>{children}</Main_Section>
              <Pricing />
            </div>
          </MainWrapper>
          {/* <div className="sticky top-0 z-50">
            <div className="shadow-md bg-white">
              <Header />
            </div>
          </div>
          <div className="flex w-screen overflow-hidden">
            <Action_Buttons />
            <Main_Section>{children}</Main_Section>
            <Pricing />
          </div> */}
        </CookieProvider>
      </body>
    </html>
  );
}
